[package]
name = "rust-audio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
anyhow = "1.0.41"
clap = "2.33.3"
oorandom = "11.1.3"
